version: "3.9"

services: 
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    # Automatically update files in the docker server
    volumes: 
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"