# Generated by Django 3.2.19 on 2023-05-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230531_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredient',
            new_name='Ingredients',
        ),
    ]
